import sys
import traceback
from engine.core.ids import TGObject

# Event type IDs.  SDK uses int constants from App.py; here we pick a stable
# value that won't collide with the SDK's ET_INPUT_FIRE_* range (those are
# Appc-side constants exposed via App.py:13834+).
ET_KEYBOARD_EVENT: int = 0x1000
ET_WEAPON_HIT:     int = 0x1100  # reserved range above input-event ids
ET_WARP_BUTTON_PRESSED: int = 0x1200   # warp button activated (synthesized from CEF Set Course)


class TGEvent(TGObject):
    def __init__(self):
        super().__init__()
        self._event_type: int = 0
        self._destination: "TGEventHandlerObject | None" = None
        self._source: "TGObject | None" = None

    def SetEventType(self, event_type: int) -> None:
        self._event_type = event_type

    def GetEventType(self) -> int:
        return self._event_type

    def SetDestination(self, dest: "TGEventHandlerObject") -> None:
        self._destination = dest

    def GetDestination(self) -> "TGEventHandlerObject | None":
        return self._destination

    def SetSource(self, source: "TGObject") -> None:
        self._source = source

    def GetSource(self) -> "TGObject | None":
        return self._source


def TGEvent_Create() -> TGEvent:
    return TGEvent()


class TGBoolEvent(TGEvent):
    """Boolean-carrying event subclass.  Used by ET_INPUT_FIRE_* events to
    signal bFiring=1 (start) / bFiring=0 (stop).  See sdk/Build/scripts/
    TacticalInterfaceHandlers.py:391 — FireWeapons reads pEvent.GetBool()."""
    def __init__(self):
        super().__init__()
        self._value: int = 0

    def SetBool(self, v) -> None:
        self._value = 1 if v else 0

    def GetBool(self) -> int:
        return self._value


def TGBoolEvent_Create() -> TGBoolEvent:
    return TGBoolEvent()


class TGKeyboardEvent(TGEvent):
    """Carries a unicode key code + key state (KS_KEYDOWN / KS_KEYUP).
    Generated by g_kInputManager when a registered key transitions; consumed
    by g_kKeyboardBinding which translates it into ET_INPUT_FIRE_* events.
    """
    KS_KEYDOWN   = 0
    KS_KEYUP     = 1
    KS_KEYREPEAT = 2
    KS_NORMAL    = 3   # character-input event (e.g. printable keys)

    def __init__(self):
        super().__init__()
        self._event_type = ET_KEYBOARD_EVENT
        self._unicode_key: int = 0
        self._key_state: int = 0

    def SetUnicodeKey(self, k) -> None:
        self._unicode_key = int(k)

    def GetUnicodeKey(self) -> int:
        return self._unicode_key

    def SetKeyState(self, s) -> None:
        self._key_state = int(s)

    def GetKeyState(self) -> int:
        return self._key_state


class WeaponHitEvent(TGEvent):
    """Weapon-impact event.  Broadcast by engine.appc.combat.apply_hit
    after damage is routed.  Mission scripts subscribe to ET_WEAPON_HIT
    (per-ship or broadcast) to react — e.g. MissionLib.FriendlyFireHandler
    triggers XO dialogue when the player damages a friendly NPC.

    Inherits TGEvent's _source / Set/GetSource for the firing ship; the
    weapon-specific surface adds target, damage, hit-point, subsystem,
    surface normal, splash radius (the radius the attribution resolver
    used for this hit), and a hull-vs-shield flag.

    `IsHullHit()` returns 1 when the hit reached the hull and 0 when the
    shield facing absorbed it. SDK conditions Conditions/ConditionAttacked
    and Conditions/ConditionAttackedBy read it to split hull damage from
    shield damage (1 → AddShipDamage, 0 → AddShieldDamage).
    """
    def __init__(self, is_hull_hit=False):
        super().__init__()
        self._event_type = ET_WEAPON_HIT
        self._target = None
        self._damage: float = 0.0
        self._hit_point = None
        self._subsystem = None
        self._normal = None
        self._radius: float = 0.0
        self._is_hull_hit: int = 1 if is_hull_hit else 0

    def GetTarget(self):              return self._target
    def SetTarget(self, tgt) -> None: self._target = tgt
    def GetDamage(self) -> float:     return self._damage
    def SetDamage(self, v) -> None:   self._damage = float(v)
    def GetHitPoint(self):            return self._hit_point
    def SetHitPoint(self, p) -> None: self._hit_point = p
    def GetSubsystem(self):           return self._subsystem
    def SetSubsystem(self, s) -> None: self._subsystem = s
    def GetNormal(self):              return self._normal
    def SetNormal(self, n) -> None:   self._normal = n
    def GetRadius(self) -> float:     return self._radius
    def SetRadius(self, r) -> None:   self._radius = float(r)

    def IsHullHit(self) -> int:
        """1 if the hit reached the hull, 0 if shields absorbed it.
        Read by Conditions/ConditionAttacked + ConditionAttackedBy."""
        return self._is_hull_hit
    def SetHullHit(self, v) -> None:  self._is_hull_hit = 1 if v else 0

    def GetFiringObject(self):
        """SDK alias for GetSource() — SelectTarget's DamageEvent
        handler reads via GetFiringObject."""
        return self.GetSource()


class ObjectExplodingEvent(TGEvent):
    """Object-started-exploding event.  Broadcast by engine.appc.ship_death
    when a ship begins its death throes (ET_OBJECT_EXPLODING).  Mission scripts
    subscribe (per-mission or broadcast) to detect kills — e.g.
    MissionLib.ObjectStartedExploding reads GetFiringPlayerID() to detect the
    player destroying a friendly and raise ET_FRIENDLY_FIRE_GAME_OVER.

    Mirrors the SDK's ObjectExplodingEvent (sdk/.../App.py:6284+), which — like
    WeaponHitEvent, and unlike the base TGEvent — carries a firing-player-id.
    That id is the killer ship's GetObjID() (BC compares it against
    pPlayer.GetObjID()); NULL_ID (0) means no attributable killer.
    """
    def __init__(self):
        super().__init__()
        self._firing_player_id: int = 0

    def SetFiringPlayerID(self, player_id) -> None:
        self._firing_player_id = int(player_id)

    def GetFiringPlayerID(self) -> int:
        return self._firing_player_id


def ObjectExplodingEvent_Create() -> ObjectExplodingEvent:
    return ObjectExplodingEvent()


def _resolve_handler(qualified_name: str):
    """Resolve 'module.func' to the callable, or None if not found."""
    dot = qualified_name.rfind(".")
    if dot == -1:
        return None
    mod_name, func_name = qualified_name[:dot], qualified_name[dot + 1:]
    mod = sys.modules.get(mod_name)
    if mod is None:
        return None
    return getattr(mod, func_name, None)


class TGEventHandlerObject(TGObject):
    def __init__(self):
        super().__init__()
        # {event_type: [qualified_handler_name, ...]}  (registration order)
        self._handlers: dict[int, list[str]] = {}
        # In-flight dispatch frames (one per nested ProcessEvent on this
        # object) so CallNextHandler can advance the handler chain. Eager init
        # so TGObject.__getattr__ never vends a truthy _Stub for it.
        self._dispatch_stack: list = []

    def AddPythonFuncHandlerForInstance(self, event_type: int, qualified_name: str) -> None:
        self._handlers.setdefault(event_type, []).append(qualified_name)

    def RemoveHandlerForInstance(self, event_type: int, qualified_name: str) -> None:
        handlers = self._handlers.get(event_type, [])
        if qualified_name in handlers:
            handlers.remove(qualified_name)

    def RemoveAllInstanceHandlers(self) -> None:
        self._handlers.clear()

    def ProcessEvent(self, event: TGEvent) -> None:
        """Dispatch through this object's instance-handler chain, BC-faithfully.

        BC's handler chain is LIFO: the MOST-RECENTLY-registered handler runs
        first, and control passes to the next (older) handler ONLY when a
        handler calls ``pObject.CallNextHandler(pEvent)``. A handler that
        returns without calling it STOPS the chain. This is load-bearing: on
        the Helm menu both HelmMenuHandlers.Hail (registered first, at bridge
        load) and E1M2.HailHandler (registered later, at mission init) handle
        ET_HAIL. HailHandler runs first, handles "Haven"/"Facility", and
        returns without CallNextHandler — so the generic Hail "no response"
        never fires and the mission's Soams sequence runs cleanly. Running all
        handlers forward (the old behaviour) let both fire, so hailing the
        colony played "no response" and stepped on the mission dialogue."""
        names = self._handlers.get(event.GetEventType(), [])
        if not names:
            return
        frame = [list(reversed(names)), 0, event]   # [chain, next_index, event]
        self._dispatch_stack.append(frame)
        try:
            self._invoke_next_handler(frame)
        finally:
            self._dispatch_stack.pop()

    def _invoke_next_handler(self, frame) -> None:
        chain, index, event = frame[0], frame[1], frame[2]
        if index >= len(chain):
            return
        frame[1] = index + 1
        fn = _resolve_handler(chain[index])
        if fn is None:
            # Unresolvable handler (module/func gone) — skip to the next rather
            # than silently stalling the chain (which would drop the default).
            self._invoke_next_handler(frame)
            return
        # Exceptions propagate: the gameloop harness relies on a crashing
        # handler surfacing as a loop failure (test_loop_fail_bad_timer), and
        # button-click dispatch swallows+logs at SendActivationEvent.
        fn(self, event)

    def CallNextHandler(self, event=None) -> None:
        """Pass control to the next (older) handler in the chain currently
        dispatching on this object. No-op outside a dispatch — SDK handlers
        call it defensively, and it's the chain terminator when the current
        handler is the oldest."""
        if self._dispatch_stack:
            self._invoke_next_handler(self._dispatch_stack[-1])


class TGPythonInstanceWrapper(TGEventHandlerObject):
    """Bridge between TGEventHandlerObject (the event-manager's destination
    type) and a Python instance's named methods. SDK conditions use this to
    receive events at a wrapper and dispatch to a method on the wrapped
    Python instance.

    Pattern (from sdk/.../Conditions/ConditionExists.py):
        self.pEventHandler = App.TGPythonInstanceWrapper()
        self.pEventHandler.SetPyWrapper(self)
        App.g_kEventManager.AddBroadcastPythonMethodHandler(
            App.ET_DELETE_OBJECT_PUBLIC, self.pEventHandler, "Deleted", obj)
    """
    def __init__(self):
        super().__init__()
        self._py_wrapper = None
        # Dict initialized eagerly because TGObject.__getattr__ returns a
        # _Stub (not None) for missing attrs, so the lazy `getattr(..., None)`
        # idiom would silently mis-route registrations into a throwaway Stub.
        self._method_handlers: dict[int, list[str]] = {}

    def SetPyWrapper(self, instance) -> None:
        self._py_wrapper = instance

    def GetPyWrapper(self):
        return self._py_wrapper

    def AddPythonMethodHandlerForInstance(self, event_type: int, method_name: str) -> None:
        """Register a self-targeted method handler. Used by SDK conditions
        that listen for events sent directly to the wrapper (e.g. timer
        events) rather than broadcast across the bus."""
        self._method_handlers.setdefault(event_type, []).append(method_name)

    def ProcessEvent(self, event):
        """Dispatch a direct-to-wrapper event to the registered method on
        the wrapped Python instance. Overrides the parent's qualified-
        function dispatch since this wrapper uses instance methods."""
        names = self._method_handlers.get(event.GetEventType(), [])
        py = self._py_wrapper
        if py is None:
            return
        for name in names:
            fn = getattr(py, name, None)
            if fn is not None:
                fn(event)


class TGEventManager(TGObject):
    def __init__(self):
        super().__init__()
        # {event_type: [(dest_obj, qualified_name), ...]}
        self._broadcast_handlers: dict[int, list[tuple["TGEventHandlerObject", str]]] = {}
        # {event_type: [(wrapper, method_name, target), ...]}; eager init —
        # see TGPythonInstanceWrapper note about TGObject.__getattr__ stubs.
        self._method_handlers: dict[
            int, list[tuple["TGPythonInstanceWrapper", str, object]]
        ] = {}

    def AddBroadcastPythonFuncHandler(
        self, event_type: int, dest: "TGEventHandlerObject", qualified_name: str, *extra
    ) -> None:
        self._broadcast_handlers.setdefault(event_type, []).append((dest, qualified_name))

    def AddBroadcastPythonMethodHandler(
        self, event_type: int, wrapper: "TGPythonInstanceWrapper",
        method_name: str, target=None,
    ) -> None:
        """Method-based broadcast handler. Mirrors AddBroadcastPythonFuncHandler
        but dispatches `getattr(wrapper.GetPyWrapper(), method_name)(evt)`
        instead of a module-qualified function. `target` (if given) restricts
        dispatch to events whose destination matches `target` by identity;
        None matches all events of `event_type`."""
        self._method_handlers.setdefault(event_type, []).append(
            (wrapper, method_name, target)
        )

    def RemoveBroadcastHandler(
        self, event_type: int, dest_or_wrapper, qualified_name_or_method: str,
        target=None,
    ) -> None:
        """Remove a previously-added broadcast handler.

        Supports both `(eType, dest, qualified_name)` (func handler, legacy)
        and `(eType, wrapper, method_name[, target])` (method handler, new).
        Falls through to the func-handler list first; if not found there,
        tries the method-handler list."""
        # Func handlers: (dest, qualified_name) tuples.
        func_handlers = self._broadcast_handlers.get(event_type, [])
        entry = (dest_or_wrapper, qualified_name_or_method)
        if entry in func_handlers:
            func_handlers.remove(entry)
            return
        # Method handlers: (wrapper, method_name, target) tuples.
        method_handlers = self._method_handlers.get(event_type, [])
        entry_m = (dest_or_wrapper, qualified_name_or_method, target)
        if entry_m in method_handlers:
            method_handlers.remove(entry_m)

    RemoveBroadcastHandlerForInstance = RemoveBroadcastHandler

    def AddEvent(self, event: TGEvent) -> None:
        # Destination dispatch is deliberately UNguarded: engine-internal
        # actions rely on ProcessEvent exceptions propagating (see
        # test_loop_fail_bad_timer). Broadcast dispatch below is
        # log-and-continue, matching original BC: embedded CPython printed
        # the traceback and the engine kept ticking, so one broken SDK
        # handler never killed the loop.
        dest = event.GetDestination()
        if dest is not None and isinstance(dest, TGEventHandlerObject):
            dest.ProcessEvent(event)
        # Func-broadcast handlers (existing).
        for bd, name in self._broadcast_handlers.get(event.GetEventType(), []):
            fn = _resolve_handler(name)
            if fn is not None:
                try:
                    fn(bd, event)
                except Exception:
                    self._log_broadcast_failure(name, event)
        # Method-broadcast handlers (new).
        for wrapper, method_name, target in self._method_handlers.get(
            event.GetEventType(), []
        ):
            if target is not None and event.GetDestination() is not target:
                continue
            py = wrapper.GetPyWrapper()
            if py is not None:
                method = getattr(py, method_name, None)
                if method is not None:
                    try:
                        method(event)
                    except Exception:
                        self._log_broadcast_failure(
                            "%s.%s" % (type(py).__name__, method_name), event
                        )

    @staticmethod
    def _log_broadcast_failure(handler_desc: str, event: TGEvent) -> None:
        """Print the active exception's full traceback to stderr, prefixed
        with a line pinpointing the failing handler + event type. Always on
        (never dev-mode-gated): a silently-swallowed handler crash is worse
        than a noisy log."""
        print(
            "[events] broadcast handler %r raised for event type %s "
            "— continuing" % (handler_desc, event.GetEventType()),
            file=sys.stderr,
        )
        traceback.print_exc(file=sys.stderr)
