#!/usr/bin/env python3
"""
list_nif_blocks.py — list every block type name appearing in BC NIF files.

BC NIFs are NIF v3.1, which lacks a block-type table. This tool scans each
file for length-prefixed ASCII strings that match block type names (start
with capital letter, all alphanumeric/underscore, plausible length). The
last such string in every BC NIF is the sentinel "End Of File".

Some false positives are possible (random bytes inside a block body that
coincidentally look like a length-prefixed ASCII name). Inspect the manifest
output and remove obvious garbage; for BC's asset set this is rare.
"""
from __future__ import annotations

import argparse
import re
import struct
import sys
from collections import defaultdict
from pathlib import Path

# Heuristic: a candidate length is in [2, 64]; the bytes that follow must be
# all printable ASCII matching this regex.
TYPE_NAME_PATTERN = re.compile(r"^[A-Z][A-Za-z0-9 ]+$")
MIN_LEN = 2
MAX_LEN = 64


def find_binary_start(buf: bytes) -> int:
    """Return the byte offset of the first plausible length-prefixed string,
    skipping the multi-line vendor text at the start."""
    # The text header ends with \n on some line, after which the next 4
    # bytes form a uint32 length. Walk newline-by-newline, then test.
    offset = 0
    while offset < len(buf):
        nl = buf.find(b"\n", offset)
        if nl < 0:
            break
        candidate = nl + 1
        if candidate + 4 > len(buf):
            return -1
        length = struct.unpack_from("<I", buf, candidate)[0]
        if MIN_LEN <= length <= MAX_LEN and candidate + 4 + length <= len(buf):
            chunk = buf[candidate + 4: candidate + 4 + length]
            try:
                s = chunk.decode("ascii")
                if TYPE_NAME_PATTERN.match(s):
                    return candidate
            except UnicodeDecodeError:
                pass
        offset = candidate
    return -1


def scan_for_type_names(buf: bytes, start: int):
    """Yield (offset, type_name) for every plausible length-prefixed ASCII
    name in the buffer from `start` onwards."""
    seen = set()
    i = start
    while i + 4 <= len(buf):
        length = struct.unpack_from("<I", buf, i)[0]
        if MIN_LEN <= length <= MAX_LEN and i + 4 + length <= len(buf):
            chunk = buf[i + 4: i + 4 + length]
            try:
                s = chunk.decode("ascii")
            except UnicodeDecodeError:
                i += 1
                continue
            if TYPE_NAME_PATTERN.match(s):
                yield i, s
                seen.add(s)
                i += 4 + length
                continue
        i += 1


def inventory_file(path: Path):
    buf = path.read_bytes()
    start = find_binary_start(buf)
    if start < 0:
        raise ValueError("could not locate binary section after text header")
    counts: dict[str, int] = defaultdict(int)
    last_seen = None
    for off, name in scan_for_type_names(buf, start):
        counts[name] += 1
        last_seen = name
    if last_seen != "End Of File":
        # Not a hard failure but a sanity warning — file may be truncated or
        # tool's heuristic missed something.
        pass
    return counts, last_seen


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("paths", nargs="+", type=Path)
    ap.add_argument("--manifest", type=Path,
                    help="Write Markdown manifest to this path")
    args = ap.parse_args()

    per_file = {}
    aggregate: dict[str, int] = defaultdict(int)
    failures: list[tuple[Path, str]] = []

    for p in args.paths:
        try:
            counts, last = inventory_file(p)
            per_file[p] = (counts, last)
            for t, c in counts.items():
                aggregate[t] += c
        except Exception as e:
            failures.append((p, str(e)))

    if args.manifest:
        with args.manifest.open("w") as out:
            out.write("# v1 Block Manifest (NIF v3.1)\n\n")
            out.write("Generated by `tools/list_nif_blocks.py`. Do not edit by hand.\n\n")
            out.write("## Files surveyed\n\n")
            for p, (counts, last) in sorted(per_file.items(), key=lambda x: str(x[0])):
                eof_status = "EOF reached" if last == "End Of File" else f"WARNING: last block was {last!r}, not End Of File"
                out.write(f"- `{p}` — {sum(counts.values())} blocks, {len(counts)} unique types ({eof_status})\n")
            if failures:
                out.write("\n## Files that failed to parse\n\n")
                for p, err in failures:
                    out.write(f"- `{p}` — {err}\n")
            out.write("\n## Block types (aggregate, sorted)\n\n")
            out.write("| Block type | Total count | Files containing |\n")
            out.write("|---|---:|---:|\n")
            for t in sorted(aggregate):
                files_containing = sum(1 for (counts, _) in per_file.values() if t in counts)
                out.write(f"| `{t}` | {aggregate[t]} | {files_containing} |\n")
        print(f"Wrote {args.manifest}")
    else:
        for t in sorted(aggregate):
            print(f"{aggregate[t]:6d}  {t}")

    return 0 if not failures else 1


if __name__ == "__main__":
    sys.exit(main())
